-- vim.cmd [[
--   augroup HighlightFifthLineAboveCursor
--     autocmd!
--     autocmd CursorMoved * lua HighlightFifthLineAboveCursor()
--   augroup END
-- ]]
--
-- function HighlightFifthLineAboveCursor()
--   local current_line = vim.fn.line('.')
--   local target_line = current_line - 5
--
--   -- Clear previous highlights
--   if vim.g.highlight_fifth_line_above_cursor_match_id then
--     vim.fn.matchdelete(vim.g.highlight_fifth_line_above_cursor_match_id)
--   end
--
--   -- Highlight the fifth line above the cursor
--   if target_line > 0 then
--     -- vim.cmd('highlight CursorLineNr guifg=#ff0000') -- Set your desired color here
--     vim.g.highlight_fifth_line_above_cursor_match_id = vim.fn.matchadd('CursorLineNr ', '\\%' .. target_line .. 'l')
--   end
-- end
